apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: python-app
  labels:
    app: helloworld-demo-pytho
spec:
  replicas: 7
  selector:
    matchLabels:
      app: helloworld-demo-pytho
  template:
    metadata:
      labels:
        app: helloworld-demo-pytho
    spec:
      containers:
      - name: helloworld-demo-pytho
        image: kandikattusumanth/helloworld-demo-pytho:KS
        ports:
        - containerPort: 8080
